name: absensi_te
version: 1.0.0+1
publish_to: none
description: Absensi TimeExcelindo
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  lottie: 2.3.2
  salomon_bottom_bar: 3.3.2
  fl_chart: 0.62.0
  flutter:
    sdk: flutter
  syncfusion_flutter_datepicker: ^21.2.6
  intl: ^0.18.1
  dropdown_search: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
