name: absensi_te
version: 1.0.0+1
publish_to: none
description: Absensi TimeExcelindo
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.13.0
  lottie: 2.3.2
  salomon_bottom_bar: 3.3.2
  fl_chart: 0.62.0
  firebase_auth: 4.6.1
  cloud_firestore: 4.7.1
  dropdown_search: ^3.0.1
  http: ^1.0.0
  dio: 5.1.2
  transitioned_indexed_stack: 1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
    - assets/icons/
  uses-material-design: true

