// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BY-7EHR8y37uBBRC0GihrzG4tT1vJ4g',
    appId: '1:49667871988:web:7e8eab6356d979af433aa1',
    messagingSenderId: '49667871988',
    projectId: 'absensi-timeexcelindo',
    authDomain: 'absensi-timeexcelindo.firebaseapp.com',
    storageBucket: 'absensi-timeexcelindo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzhcDuhijbYMKSH8_yn2FIW6kPAqwU4h0',
    appId: '1:49667871988:android:88ee97fb3d34e14a433aa1',
    messagingSenderId: '49667871988',
    projectId: 'absensi-timeexcelindo',
    storageBucket: 'absensi-timeexcelindo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj4V3MO0VeTOgme6NQiRbSVTzoq1FGqmE',
    appId: '1:49667871988:ios:70faf062f206b6d2433aa1',
    messagingSenderId: '49667871988',
    projectId: 'absensi-timeexcelindo',
    storageBucket: 'absensi-timeexcelindo.appspot.com',
    iosClientId: '49667871988-8s0n9qhm6vnugfk7u8879tfncurioce2.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj4V3MO0VeTOgme6NQiRbSVTzoq1FGqmE',
    appId: '1:49667871988:ios:70faf062f206b6d2433aa1',
    messagingSenderId: '49667871988',
    projectId: 'absensi-timeexcelindo',
    storageBucket: 'absensi-timeexcelindo.appspot.com',
    iosClientId: '49667871988-8s0n9qhm6vnugfk7u8879tfncurioce2.apps.googleusercontent.com',
    iosBundleId: 'com.example.absensiCli',
  );
}
